server:
  port: 8080

spring:
  mvc:
    validation:
      jakarta:
        enabled: true
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=sensitiveWords
    username: username
    password: Strongpa$$word
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      pool-name: MyHikariCP
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
